# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 21:16

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import project_share.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_share', '0017_auto_20170405_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=255, verbose_name='State or Province'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('CSNAP', 'cSnap'), ('BLOCK', 'Blockly/Scratch')], max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='application_screenshot/'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='f',
            field=models.FileField(upload_to='files/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='when_created',
            field=project_share.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='when_modified',
            field=project_share.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='Last Changed'),
        ),
    ]
